##
## テストアプリ
##
---
## デプロイメント 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-counter
  template:
    metadata:
      labels:
        app: my-counter
    spec:
      containers:
      - name: my-counter
        #image: harbor.labo.local/tkr/my-counter:1.0
        image: maho/my-counter:1.0
        imagePullPolicy: Always
---
## サービス
apiVersion: v1
kind: Service
metadata:
  name: my-counter
spec:
  selector:
    app: my-counter
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
